# Generated by Django 5.1.6 on 2025-02-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='belligerants',
            new_name='belligerents',
        ),
    ]
