# Generated by Django 5.1.6 on 2025-02-19 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('reliability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'The minimum reliability value is 0.'), django.core.validators.MaxValueValidator(5, 'The maximum reliability value is 5.')])),
                ('text', models.TextField()),
                ('book', models.CharField(blank=True, max_length=200, null=True)),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citation', to='wars.war')),
            ],
        ),
    ]
