# Generated by Django 5.1.6 on 2025-02-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
        ('wars', '0002_rename_enddate_war_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='wars.war'),
        ),
    ]
