# Generated by Django 5.1.6 on 2025-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('procedence', models.CharField(blank=True, choices=[('ROM', 'Roman'), ('GRK', 'Greek'), ('CAR', 'Carthaginian'), ('ITA', 'Italian'), ('HIS', 'Iberian'), ('GAU', 'Gaul'), ('GER', 'Germanic'), ('BRI', 'Brittanic'), ('PON', 'Pontic'), ('ARM', 'Armenian'), ('PER', 'Persian'), ('EGP', 'Egyptian'), ('MAU', 'Mauretanian'), ('NUM', 'Numidian'), ('PAR', 'Parthian')], max_length=100, null=True)),
            ],
        ),
    ]
